language: node_js
node_js:
- '7'
deploy:
  provider: npm
  email: kian.peymani@gmail.com
  api_key:
    secure: WRSNz0BhBbu2CcznxqaX0RPuxuZi8O8ydaxdVwYsY9Fl/iZpQPPKNHX5vFGgiNh31MHtEerGw0bhOoNe37AtLTdPYP6i5OzPvaY6w4O2uk1y+rHlzHXg4+rQLC4+cGcfpcVr3QxKIilgxguEERAVAIHbsp4H11ogjgr5C1puqTZFyakh/ngM45pBFYhHToK1XQw+o/abbqIdHm/TYIBPn/uXQZXu7qsnmS5a8UtROMxKkvEjxlip2LM1DrfTIgaGprGcCp+X1tpFSoEUUvsjOsleS9z1pXKJLqVhFdPThli7XdTBEEQDppWj70H8OhcE1l1TdqR8H4w4DGNyn0dfa9w+VpVP4tGDJXs4IHjqFFaryU0a2CbfkdUlNx1dereJLMWQzTqJRk0n3jfQJG//+qD7AXmu7zCO0dPD8rD91QsNaA1Q0j5gHw6OBYo0oxpBLbSNx3sUT+CdAU8xkT2VkpoZLCjnyeohONWMD/7lM8+xhY/Q38Bq3HvX9fRXTHX6bsRr/G/lbnU31peZxrvr2TnyvurPowmk6S6wih6Hfkk9UftbansRe1UmAqKGJxEBFmsCPT2Y24FrQbwolSYle9FjnM1rtIMF2o1cNGjQ8tPD4BVo4Z5mkutvACFpP1B7tIfKUYDbpubOmiQfCnX4fo1Iv03jo1zjA0v5qul/3aA=
  on:
    repo: node-xyz/xyz-cli
    branch: master
